root: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
env:
  node: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
rules:
  semi:
    - error
    - always
#   '@typescript-eslint/strict-boolean-expressions':
#     - 2
#     - allowString: false
#       allowNumber: false
ignorePatterns:
  - src/**/*.test.ts
  - src/frontend/generated/*
